spring:
  jpa:
    database: H2
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        query.in_clause_parameter_padding: true
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
