spring:
  jpa:
    database: H2
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.in_clause_parameter_padding: true

  h2:
    console:
      enabled: true
